### ISSUE TITLE
directoryentry failing test with 2.2.0.0

### ISSUE THREAD

**Issue by mzf-guest** [Zipios/Zipios#29] opened 2019-04-24 17:18 UTC
Hello,

I'm trying to update the Debian Zipios package to 2.x version.

I've recently updated to 2.2.0.0 and I got DirectoryEntry test failing:

```
-------------------------------------------------------------------------------
Scenario: DirectoryEntry for a valid directory
     Given: test an existing directory and no comment
      When: setting the Unix time
      Then: we take it as is
-------------------------------------------------------------------------------
/tmp/building/package/tests/directoryentry.cpp:1726
...............................................................................

/tmp/building/package/tests/directoryentry.cpp:1740: FAILED:
  REQUIRE( de.getUnixTime() == dr.getUnixTimestamp() )
with expansion:
  348730759 == 348730760

===============================================================================
test cases:      35 |      34 passed | 1 failed
assertions: 2608186 | 2608185 passed | 1 failed
```

The tests were successful with the 2.1.7.11.

My working repository is at https://salsa.debian.org/mzf-guest/zipios

I suspect a rounding issue as the expanded values are very close (348730759 <=> 348730760).

Could you please provide help?

**Comment by russel** [comment] 2019-04-24 19:14
I tried running the tests on Debian Sid with Zipios master/HEAD, and:
```
|> ./tests/zipios_tests 
zipios_tests[28871]: version 2.2.0, seed is 1556130144
===============================================================================
All tests passed (4472455 assertions in 35 test cases)

|> 
```

**Comment by AlexisWilke** [comment] 2019-04-25 07:48
Of course, the tests passed for me too before I created version 2.2.0.0. :-)

### Rounding you say?

The DOS Time only records even seconds. This is the rounding you're bumping into.

### Why would the test fail for you, though?

I actually make heavy use of `rand()` and reset the generated with `srand(time(NULL))` by default. So you could get an error once in a while. The seed (1556130144 in Russel's example) is important to try to reproduce the problem. I actually use the seed which is defaulted to `time(NULL)` if not specified on the test command line.

So because of these random values each person running the tests may get a slightly different result, myself included. That is, if I run the tests 100 times, it is likely that each time I'll get a different stream from `rand()`.

### Okay, so what happened?

I was trying to verify that the date was correct and... it's not being saved as a DOS date in the FileEntry object (the DirectoryEntry derives from FileEntry). This is why we get the error, once in a while.

This means the `getUnixTime()` returns `r` and not a DOS time value. So I'm fixing the test with:

    REQUIRE(de.getUnixTime() == r);

**Comment by AlexisWilke** [comment] 2019-04-25 07:49
@mzf-guest Okay, I pushed the fix. Let me know whether you can still reproduce the problem.

Thank you.
Alexis

**Comment by russel** [comment] 2019-04-25 09:51
I got a slightly different result this time, but still all passing and green:
```
|> ./tests/zipios_tests 
zipios_tests[18306]: version 2.2.0, seed is 1556183549
===============================================================================
All tests passed (3331976 assertions in 35 test cases)

|> 
```

**Comment by mzf-guest** [comment] 2019-04-25 17:56
```
/usr/bin/ctest --force-new-ctest-process -j1
Test project /tmp/building/package/obj-x86_64-linux-gnu
    Start 1: zipios_tests
1/1 Test #1: zipios_tests .....................   Passed  284.60 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) = 284.61 sec
```

Thanks a lot for the quick fix!
I guest you'll soon tag a new release including the fix?

**Comment by AlexisWilke** [comment] 2019-04-26 03:41
https://github.com/Zipios/Zipios/releases/tag/v2.2.1.0

Thanks for checking.

**Comment by dooglio** [comment] 2019-04-26 03:42
@AlexisWilke why no PR?

**Closed by AlexisWilke** 2019-04-26 03:41 UTC

**Comment by AlexisWilke** [comment] 2019-04-26 04:23
I don't see the point for changing a test with two lines of changes.

**Comment by dooglio** [comment] 2019-04-26 13:57
For posterity and visibility. Plus it's good practice.

**Comment by mzf-guest** [comment] 2019-04-26 18:23
@AlexisWilke I've updated the package with the 2.2.1.0 release and the tests are success. Thanks!
