### ISSUE TITLE
Test executable compile failure with GCC 7

### ISSUE THREAD

**Issue by hobbes1069** [Zipios/Zipios#5] opened 2017-02-19 17:18 UTC
Importing this bug from sourceforge:
https://sourceforge.net/p/zipios/bugs/10/

```
[ 79%] Building CXX object tests/CMakeFiles/zipios_tests.dir/common.cpp.o
cd /builddir/build/BUILD/zipios-2.1.1/build/tests && /usr/bin/c++    -I/builddir/build/BUILD/zipios-2.1.1 -I/builddir/build/BUILD/zipios-2.1.1/build -I/usr/include/catch  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -std=c++11 -fPIC   -o CMakeFiles/zipios_tests.dir/common.cpp.o -c /builddir/build/BUILD/zipios-2.1.1/tests/common.cpp
In file included from /usr/include/catch/catch.hpp:34:0,
                 from /builddir/build/BUILD/zipios-2.1.1/tests/tests.hpp:35,
                 from /builddir/build/BUILD/zipios-2.1.1/tests/backbuffer.cpp:27:
/builddir/build/BUILD/zipios-2.1.1/tests/backbuffer.cpp: In function 'void ____C_A_T_C_H____T_E_S_T____35()':
/builddir/build/BUILD/zipios-2.1.1/tests/backbuffer.cpp:72:58: error: expected primary-expression before 'bb'
                     REQUIRE_THROWS_AS(zipios::BackBuffer bb(is, zipios::VirtualSeeker(), i), zipios::InvalidException);
                                                          ^
/builddir/build/BUILD/zipios-2.1.1/tests/backbuffer.cpp:72:58: error: expected ')' before 'bb'
/builddir/build/BUILD/zipios-2.1.1/tests/backbuffer.cpp:80:54: error: expected primary-expression before 'bb'
                 REQUIRE_THROWS_AS(zipios::BackBuffer bb(is), zipios::IOException);
                                                      ^
/builddir/build/BUILD/zipios-2.1.1/tests/backbuffer.cpp:80:54: error: expected ')' before 'bb'
/builddir/build/BUILD/zipios-2.1.1/tests/backbuffer.cpp:82:54: error: expected primary-expression before 'bb'
                 REQUIRE_THROWS_AS(zipios::BackBuffer bb(is), zipios::InvalidException);
                                                      ^
/builddir/build/BUILD/zipios-2.1.1/tests/backbuffer.cpp:82:54: error: expected ')' before 'bb'
make[2]: *** [tests/CMakeFiles/zipios_tests.dir/build.make:90: tests/CMakeFiles/zipios_tests.dir/backbuffer.cpp.o] Error 1
```

**Comment by russel** [comment] 2017-02-19 18:05
I find there are more problems using G++ 7.0.1 on Fedora Rawhide. I have put out a request to someone involved in GCC and the library to see what the right solution is for us so as to maintain GCC 5, 6, and 7 compilability.

**Comment by hobbes1069** [comment] 2017-02-19 18:11
I got a "good build" by disabling all the testing stuff but I did see several deprecated warnings...

**Comment by AlexisWilke** [comment] 2017-02-19 23:07
I'm creating an Ubuntu 16.10 VM to test this... The tests are pretty stringent (as to really test many possibilities), so I am not too surprised that they need updating over time to continue to work.

**Comment by AlexisWilke** [comment] 2017-02-21 05:51
I ran a first round with Ubuntu 16.10. This was with g++ 6.2.0. The result was that the test passed.

There were code changes already to avoid the warnings. So it should be warning free on that platform by default.

Now I will try to install g++ 7.x from the PPA, here: https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test

If that works, I should be able to test with g++ 7.x and see whether I can reproduce the mentioned crash.

**Comment by AlexisWilke** [comment] 2017-02-21 06:41
Well... unfortunately, it does not look like g++ 7.x gets installed on 16.10 yet. I guess I could try with 16.04 as the PPA may not be built for 16.10 yet (possibly not everything, such as gcc/g++ 7.x.)

**Comment by russel** [comment] 2017-02-21 09:00
GCC 7 is in Debian Experimental but not in Sid. I guess Ubuntu will simply wait until the merge from Sid that has it. I do not know of a timescale. GCC 7 is now the standard for Fedora Rawhide and so will be in Fedora 26.

**Comment by hobbes1069** [comment] 2017-02-21 12:50
@AlexisWilke,

You can sign up for Fedora COPR which would allow you to do test builds in Fedora Rawhide...

https://copr.fedorainfracloud.org/

It's not quite as fully featured as the Ubuntu or OpenSUSE systems but it's fully functional.

**Comment by AlexisWilke** [comment] 2017-02-21 20:36
Is it possible to install Fedora as a server only system? Last time I tried, it only had the option to install a desktop version which is dirt slow in my VMs.

**Comment by hobbes1069** [comment] 2017-02-22 13:25
You can try the netinstall image and choose not to install a desktop...
https://download.fedoraproject.org/pub/fedora/linux/releases/25/Server/x86_64/iso/Fedora-Server-netinst-x86_64-25-1.3.iso

Or if you don't mind going through the pain of a graphical install and then switching the default runlevel afterwards:

https://fedoraproject.org/wiki/Systemd#How_do_I_change_the_default_target.3F

**Comment by AlexisWilke** [comment] 2017-02-24 22:26
Okay, that worked. I got _Fedora 25 (Server Edition)_ installed. The installer looks really nice now! A bit slow since it's graphical, but still really nice.

Now, I could install `git` and `g++` and get the source to compile, but the compiler is still version **6.3.1**, not version **7.x**. I used:

    dnf install gcc-c++

to install `g++`. Is there an easy way to get version 7 installed?

**Comment by hobbes1069** [comment] 2017-02-24 22:40
Ok, I would do two things...

```
dnf group install "Development Tools" "RPM Development Tools"
```

This will get you almost everything you need including mock which lets you build packages for other platforms. It does require an SRPM (which I can provide) but it's the easiest method because it uses a chroot and doesn't pollute your whole system with packages from another release.

mock -r fedora-rawhide-x86_64 --resultdir ~/where/you/want/to/put/them /path/to/srpm

**Comment by AlexisWilke** [comment] 2017-02-24 23:59
I thought you said that Fedora was coming with gcc 7.x. Since it's still 6.3, I do not really see why we would have to do anything about 7.x at this point. Until I can install 7.x "just like that" then only people who really need zipios on the very tip of g++ will have a need and they can always provide us with fixes if they can find how to fix problems they get. Until then, I don't want to spend more time on trying to get 7.x installed. I tried your group install and I still just have 6.3...

**Comment by hobbes1069** [comment] 2017-02-25 03:50
Fedora Rawhide is the roller development release that all future releases are branched from. Fedora 26 will be branching from Rawhide in the next couple of months, but most people don't run "Rawhide" because it can be broken frequently as Fedora is generally a bleeding edge distro. 

That being said, packages are maintained from Rawhide down so it's not possible to have a "newer" version of a package in a released version and not in Rawhide as that would lead to serious issues once branched. Getting a preview into GCC 7 this way gives us a chance to fix problems before they make it into a release.

**Comment by russel** [comment] 2017-02-25 07:58
@AlexisWilke Fedora 25 hac GCC 6.3, but Fedora 26 will have GCC 7, as @hobbes1069 says, Fedora Rawhide is the rolling release which neophytes like me run despite the dangers. It gets everything new that Red Hat want in the next Fedora release. As you say, most people in production are still running GCC 5 or 6, this is about being prepared for GCC 7 in 6 months time.

**Comment by AlexisWilke** [comment] 2017-02-25 08:58
Ah... so I should have been given a link to install version 26 then. Personally I don't care about Fedora, if it breaks, no matter. It's just to install on a VM to test Zipios... So if there is a link similar to version 25 with version 26, I could install that instead and test with g++ 7.

**Comment by russel** [comment] 2017-02-25 09:14
I believe there is no Fedora 26 install as, technically, there is no Fedora 26, as yet. I propose we treat this problem as one we cannot test in an automated fashion as yet. I run Fedora Rawhide so can see the problem, I also run Debian Sid so have the GCC 6.3 base to check nothing breaks.

**Comment by hobbes1069** [comment] 2017-02-25 13:28
@AlexisWilke,

If you still want to try Rawhide you're mostly there. You start with the latest release and then install and enable the Rawhide repo:

```
dnf install fedora-repos-rawhide
dnf config-manager --set-enabled rawhide
dnf --refresh update
```

Should do it.

**Comment by AlexisWilke** [comment] 2017-02-25 22:58
@hobbes1069 Okay! Great that worked. I now have g++ 7.0.1. Thank you.

**Comment by AlexisWilke** [comment] 2017-02-26 00:21
[Related Catch Issue](https://github.com/philsquared/Catch/issues/817)

The answer seems to be to "hide" the code in a lambda expression. I will change all those REQUIRE_THROW_AS() in that way.

**Comment by AlexisWilke** [comment] 2017-02-26 02:22
Okay, so I've got the code to compile in _Fedora 26_, but the tests that expect errors in the `iostream` class do not fail as expected. Wondering whether this is us or the C++ library not properly setting up the `fail()` flags. At least from what I can see all the failing tests are very similar errors: problems that go undetected and thus unreported.

**Comment by russel** [comment] 2017-02-27 10:54
I think I may have spotted the problem, so will take control of this one for now.

**Comment by russel** [comment] 2017-02-27 13:42
I believe this is fixed with the change set https://github.com/Zipios/Zipios/commit/71e76aabe3e2074d752fcfe2ede2e31fff52b015

**Comment by hobbes1069** [comment] 2017-02-27 13:53
Do you have something that will apply to the current 2.1.1 release? Looks like backbuffer.cpp has changed quite a bit.

**Comment by russel** [comment] 2017-02-27 14:21
A number of thoughts: I'd have thought a new release soon rather than retrofitting old releases; the Git repositories appear not to have tags or maintenance branches so it is not possible easily to do retrofitting; I'd like to get people to upgrade rather than do any maintenance. And we probably need to get this library into conan.io.

**Comment by AlexisWilke** [comment] 2017-02-27 20:05
I don't think we changed that much 2.1.1 and 2.1.5 other than the very problems you pointed out. So it should not be a big problem. Also the tests are here to verify that everything still works as expected.

The only possible problem, I would imagine, would be if we changed some of the .hpp files. But I don't think that's the case?

**Comment by AlexisWilke** [comment] 2017-02-28 05:06
@russel Okay, I saw your comments about only declaring the lambda and not actually calling them. Good catch. That explains very well why those `REQUIRE()` would fail. Now I saw those in sourceforge.net comments instead of github... I hope you checked things in github too?

**Comment by russel** [comment] 2017-02-28 06:51
I had been keeping the SourceForge Git repository up to date and that is where those emails came from. However I then totally gutted the SourceForge project, and have now deleted that repository. The project is now very much a GitHub one with a SourceForge leftover. I tried hard to come to terms with SourceForge, but compared to GitHub, BitBucket, and GitLab it is very poor. So yes the GitHub repository is the mainline and is up to date. I am now wondering whether to make GitHub pages rahter than using SourceForge for the website.

**Comment by russel** [comment] 2017-02-28 07:19
I believe this issue as initially reported has now been addressed, and this thread should be closed. I have created new issues for the two outstanding points I have from this thread. I propose if others have outstanding points, new issues be raised for them.

**Closed by russel** 2017-02-28 07:19 UTC
